# version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel
      MYSQL_USER: root2
      MYSQL_PASSWORD: sasdswsz
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot2", "-p sasdswsz"]
      # test: >
      #   CMD bash -c 'mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}'
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "3306:3306"
    # volumes:
    #   - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    volumes:
    - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
      # - tunnel
      


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - .:/var/www
      - ./storage/app/public:/var/www/storage/app/public
    # ports:
    #   - "80:80"
    command: >
      sh -c "rm -rf public/storage && php artisan storage:link && php-fpm"
    # command: sleep infinity 
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: travel
      DB_USERNAME: root2
      DB_PASSWORD: sasdswsz
    networks:
      - mynetwork



  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql_data:
